Punish:
  WEBHOOK: ""
  # Placeholders
  # {player} = Gets the player name
  # {checktype} = Gets the check type
  TITLE: "Punishment Executed"
  DESCRIPTION: "{player} has been punished for {checktype}"
Alert:
  WEBHOOK: ""
  # Placeholders
  # {player} = Gets the player name
  # {checktype} = Gets the check type
  # {vl} = Gets the vl
  TITLE: "Alert Executed"
  DESCRIPTION: "{player} has been alerted for {checktype} VL[{vl}]"
